package exercises.chapter16;

/**
 * Exercise 3
 * Write a method that creates and initializes a two-dimensional
 * array of double. The size of the array is determined by the
 * arguments of the method, and the initialization values are
 * a range determined by beginning and ending values that are also
 * arguments of the method. Create a second method that will
 * print the array generated by the first method. In main()
 * test the methods by creating and printing several
 * different sizes of arrays.
 */
public class E03_TwoDimensionalArrayOfDouble {
    static double[][] createArray(int sizeX, int sizeY, double startValue, double endValue) {
        double[][] result = new double[sizeX][sizeY];
        double increment = (endValue - startValue) / (sizeX * sizeY);
        double value = startValue;
        for (int i = 0; i < result.length; i++) {
            for (int j = 0; j < result[i].length; j++) {
                result[i][j] = value;
                value += increment;
            }
        }
        return result;
    }

    static void printDeepArray(double[][] arr) {
        for (double[] doubles : arr) {
            for (double d : doubles)
                System.out.printf("%.2f ", d);
            System.out.println();
        }
    }

    public static void main(String[] args) {
        printDeepArray(createArray(1, 7, 1.0, 99.0));
        System.out.println("********************");
        printDeepArray(createArray(2, 3, 50.0, 80.0));
        System.out.println("********************");
        printDeepArray(createArray(5, 4, 33.3, 66.6));
    }
}
/* Output:
1.00 15.00 29.00 43.00 57.00 71.00 85.00
********************
50.00 55.00 60.00
65.00 70.00 75.00
********************
33.30 34.96 36.63 38.29
39.96 41.62 43.29 44.95
46.62 48.28 49.95 51.61
53.28 54.94 56.61 58.27
59.94 61.60 63.27 64.93
 */